name: Build and Release

on:
  push:
    branches: ['**']  # Trigger on pushes to all branches

permissions:
  contents: write  # Required for creating releases

env:
  LC_ALL: C  # Set consistent locale for build environment

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full commit history

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get commit SHA
        id: sha
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Cache arduino dep downloads
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace}}/.arduino/downloads
          key: ${{ runner.os }}-arduino-downloads

      - name: Prepare build env
        run: make setup

      - name: Build software
        run: make hupfdule-model100 KALEIDOSCOPE_TEMP_PATH=${{ github.workspace}}/.kaleidoscope-temp  # Only build the hupfdule-model100 firmware

      - name: Create release with commit-based tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo eins
          # Generate unique tag name with commit SHA and timestami
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo zwei
          TAG_NAME="commit-$SHORT_SHA-$TIMESTAMP"

          git branch
          git log -1

          echo drei
          # Create GitHub release
          gh release create $TAG_NAME \
            --repo ${{ github.repository }} \
            --title "Release for $SHORT_SHA" \
            --notes $(git log -1) \

          echo vier
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            output/  # Path to your build artifacts
