name: Build & Publish

on:
  push:
    branches:
      - '**'  # Runs on pushes to any branch
  pull_request:
    branches:
      - '**'  # Runs on PRs targeting any branch
  workflow_dispatch:

permissions:
  contents: write  # Grant write access to releases

env:
  LC_ALL: C
  EXTRA_VERSION: ${{ github.run_number }}
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}   # Uses the branch that triggered the workflow instead of master
          fetch-depth: 0           # We need to fetch the full history to infer the correct version name
      - name: Add upstream remote  # We need to fetch the upstream source to be able to create the changelog of our own changes
        run: |
          git remote add upstream https://github.com/keyboardio/Chrysalis-Firmware-Bundle
          git fetch upstream
      - name: Discover the version tag
        id: version
        run: |
          TAG=$(make version-tag)
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Cache arduino dep downloads
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace}}/.arduino/downloads
          key: ${{ runner.os }}-arduino-downloads
      - run: make setup
      - run: make hupfdule-model100 KALEIDOSCOPE_TEMP_PATH=${{ github.workspace}}/.kaleidoscope-temp  # Only build the hupfdule-model100 firmware
      - name: Collect the commit SHAs of the build
        run: make collect-build-info
      - name: Add all commit logs to changelog     # Add all our commit logs to the changelog
        run: make changelog > output/firmware-changelog.md

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-build
          path: |
            output/

  publish:
    needs: build
    runs-on: ubuntu-latest
    # Ensure this job only runs on pushes to master branch
    if: github.ref == 'refs/heads/hupfdule-dev2'
    env:
      OUTPUT_DIR: artifacts/firmware-build
    steps:
      - uses: actions/checkout@v4
      - name: Discover the version tag
        id: version
        run: |
          TAG=$(make version-tag)
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create the release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          make create-gh-release
      - name: Package up the artifacts
        shell: bash
        run: |
          make package-firmware-build

      - name: Upload the firmware files & build info to the release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          make upload-gh-release
